# Generated by Django 5.0.6 on 2025-02-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
