# Generated by Django 5.0.6 on 2025-02-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0004_note_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
