# Generated by Django 5.0.6 on 2025-02-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0006_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Signup',
        ),
    ]
